# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fccfa264804e0ab3ad2a1845598416c73754fd42681c5503e84b67fba24ba2ac35aaa99cfff6557a1550725ed20c716fb0796fc47c07c7ae1fba99240e14af4

test:
  secret_key_base: 8142b7904833f74ad15f8c6c3410953209b3a02e858cc590d4f5427f6f1d8eb86e9c3bcd3b42d3f352d9fca3bcb0d03a9459340661c310dcaa6ab67e9a29cf5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
